### ISSUE TITLE
Setup not working correctly

### ISSUE THREAD

**Issue by Wyxaldir** [FieryFlames/schlub#2]
Followed setup instructions, but probably messed up somewhere.

The new webhook URL looks like this: https://schlub.fieryflames.dev/api/webhooks/API_KEY

Not sure if that's correct though. An example URL might make it easier to setup for new users. Does it still need the /github at the end?

Additionally, does SSL verification need to be on/off?

**Comment by Wyxaldir** [comment]
Noticed now that I'm getting an error in github as well: Invalid HTTP response: 400
```
Request URL: https://schlub.fieryflames.dev/api/webhooks/API_KEY
Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/ID
X-GitHub-Delivery: SOME_ID
X-GitHub-Event: star
X-GitHub-Hook-ID: ID
X-GitHub-Hook-Installation-Target-ID: ID
X-GitHub-Hook-Installation-Target-Type: repository```

**Comment by jackmthws** [comment]
Hi! To be clear, is `API_KEY` something like `12345678/abcdefg` (webhook ID and token)?
Can you get the response of that invalid http response?

**Comment by Wyxaldir** [comment]
**Header:**
Alt-Svc: h3=":443"; ma=86400
Cf-Ray: 8269fdef0d741771-IAD
Content-Length: 51
Content-Type: text/plain;charset=UTF-8
Date: Wed, 15 Nov 2023 19:44:58 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=%2FC6pUOko7ICSJsK%2B6PlFjPU589w3Za7Ww7TsYYwromDP2yA65Y12bvoNqlyPAbnxjAJCEO2gidzLbrN5lY5bc0l5lClkP2hd9I8OldzOD18Zvpaf0kAvTpvxLj3QCYypeIJnzKyJy%2BfB"}],"group":"cf-nel","max_age":604800}
Server: cloudflare

**Body:**
Invalid path: path should be webhookId/webhookToken

The only thing I changed in the path is replacing discord.com with schlub.fieryflames.dev. The API_KEY is everything else after the webhooks/ sorry if that was unclear. There's no /github at the end either, but that didn't fix it for me.

**Comment by jackmthws** [comment]
Oh, looks like I had removed some handling for the path and forgot to update the README. If you remove api/webhooks from the URL too it should start working, but please be aware this is a very new project and not many events are implemented.

**Comment by Wyxaldir** [comment]
That's 100% ok, I just use the push event myself anyway! Thanks for the clarification!

That worked btw, new format for the push looks really sleek, much appreciated!

**Comment by jackmthws** [comment]
Sorry for the issues, glad we got this resolved!
